-- EXPLORE THE DATABASE
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- EXPLORE ALL THE COLUMNS IN DATABASE
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'dim_custoemrs'

-- EXPLORE ALL COUNTRIES OUR CUSTOMERS COME FROM
SELECT DISTINCT country 
FROM  [DataWarehouseAnalytics].[gold].[dim_customers]

--EXPLORE ALL PRODUCT CATEGORIES "The Major Division"
SELECT DISTINCT category, subcategory, product_name 
FROM  [DataWarehouseAnalytics].[gold].[dim_products]
ORDER BY 1,2,3

-- DATE EXPLORATION
-- FIND THE FIRST AND THE LAST ORDER
SELECT 
MIN(order_date) first_order_date,
MAX(order_date) last_order_date,
DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS order_range_months
FROM [DataWarehouseAnalytics].[gold].[fact_sales]

-- FIND THE YOUNGEST AND THE OLDEST CUSTOMER
SELECT
MIN(birthdate) AS oldest_birdate,
DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_birhdate,
DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM  [DataWarehouseAnalytics].[gold].[dim_customers]

-- FIND THE TOTAL SALES
SELECT 
SUM(sales_amount) AS total_sales
FROM [DataWarehouseAnalytics].[gold].[fact_sales]

-- FIND HOW MANY ITEMS ARE SOLD
SELECT 
SUM(quantity) AS total_quantity
FROM [DataWarehouseAnalytics].[gold].[fact_sales]

-- FIND THE AVERAGE SELLING PRICE
SELECT 
AVG(sales_amount) AS avg_price
FROM [DataWarehouseAnalytics].[gold].[fact_sales]

-- FIND THE TOTAL NUMBER OF ORDERS
SELECT 
COUNT(order_number) AS total_orders
FROM [DataWarehouseAnalytics].[gold].[fact_sales]

-- FOR UNIQUE TOTAL ORDERS
SELECT 
COUNT(DISTINCT order_number) AS total_orders                               
FROM [DataWarehouseAnalytics].[gold].[fact_sales]

-- FIND THE TOTAL NUMBER OF PRODUCTS
SELECT 
COUNT(product_name)  AS total_product
FROM [DataWarehouseAnalytics].[gold].[dim_products]

SELECT 
COUNT(DISTINCT product_key) AS total_product
FROM [DataWarehouseAnalytics].[gold].[dim_products]

--  FIND THE TOTAL NUMBER OF CUSTOMERS
SELECT
COUNT(customer_key) AS total_customers
FROM  [DataWarehouseAnalytics].[gold].[dim_customers]


--  FIND THE TOTAL NUMBER OF CUSTOMERS THAT HAS PLACED AN ORDER
SELECT
COUNT(DISTINCT customer_key) AS total_customers
FROM  [DataWarehouseAnalytics].[gold].[fact_sales]


  

  -- GENERATE A REPORT THAT SHOWS ALL KEY METRICS OF THE BUSINESS
  SELECT 'total Sales' AS measure_name,
SUM(sales_amount) AS measure_value
FROM [DataWarehouseAnalytics].[gold].[fact_sales]
UNION ALL 
  SELECT 'tota Quantity' AS measure_name,
SUM(quantity) AS measure_value
FROM [DataWarehouseAnalytics].[gold].[fact_sales]
UNION ALL 
SELECT 'Average Price',
AVG(sales_amount) 
FROM [DataWarehouseAnalytics].[gold].[fact_sales]
UNION ALL 
SELECT 'Total Nr. Orders',
COUNT(DISTINCT order_number)                               
FROM [DataWarehouseAnalytics].[gold].[fact_sales]
UNION ALL 
SELECT 'Total Nr. Products',
COUNT(product_name)  
FROM [DataWarehouseAnalytics].[gold].[dim_products]
UNION ALL 
SELECT 'Total Nr. Customers',
COUNT(customer_key) AS total_customers
FROM  [DataWarehouseAnalytics].[gold].[dim_customers]




-- MAGENITUDE [MEASURE] BY [DIMENSION]
-- FIND THE TOTAL CUSTOMERS BY COUNTRIES
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM  [DataWarehouseAnalytics].[gold].[dim_customers]
GROUP BY country
ORDER BY total_customers DESC


-- FIND TOTAL PRODUCTS BY GENDER
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM  [DataWarehouseAnalytics].[gold].[dim_customers]
GROUP BY gender
ORDER BY total_customers DESC

-- FIND TOTAL PRODUCTS BY CATEGORY
SELECT 
category,
COUNT(product_key) AS total_products
FROM  [DataWarehouseAnalytics].[gold].[dim_products]
GROUP BY category
ORDER BY total_products DESC


-- WHAT IS THE AVERAGE COSTS IN EACH COUNTRY?
SELECT 
category,
AVG(cost) AS avg_costs
FROM  [DataWarehouseAnalytics].[gold].[dim_products]
GROUP BY category
ORDER BY avg_costs DESC


-- WHAT IS THE TOTAL REVENUE GENERATED BY EACH CATEGORY?
SELECT 
p.category,
SUM(sales_amount) AS total_revenue
FROM [DataWarehouseAnalytics].[gold].[fact_sales] f
LEFT JOIN  [DataWarehouseAnalytics].[gold].[dim_products] p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC


-- FIND THE TOTAL AVERAGE REVENUE GENRATED BY EACH CUSTOMER
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM [DataWarehouseAnalytics].[gold].[fact_sales] f
LEFT JOIN  [DataWarehouseAnalytics].[gold].[dim_customers] c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC


-- WHAT IS THE DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES?
SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM [DataWarehouseAnalytics].[gold].[fact_sales] f
LEFT JOIN  [DataWarehouseAnalytics].[gold].[dim_customers] c
ON c.customer_key = f.customer_key
GROUP BY 
c.country
ORDER BY total_sold_items DESC


-- RANKING ANALYIS (ORDER THE VALUE OF [DIMENSION] BY [MEASURE].
-- WHICH 5 PRODUCTS GENERATE THE HIGHEST REVENUE
SELECT TOP 5
p.product_name,
SUM(sales_amount) AS total_revenue
FROM [DataWarehouseAnalytics].[gold].[fact_sales] f
LEFT JOIN  [DataWarehouseAnalytics].[gold].[dim_products] p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC


-- WHICH 5 PRODUCTS GENERATE THE HIGHEST REVENUE
SELECT TOP 5
p.subcategory,
SUM(sales_amount) AS total_revenue
FROM [DataWarehouseAnalytics].[gold].[fact_sales] f
LEFT JOIN  [DataWarehouseAnalytics].[gold].[dim_products] p
ON p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY total_revenue DESC


-- WHAT ARE THE 5 WORST-PERFORMING PRODUCTS IN TERMS OF SALES
SELECT TOP 5
p.product_name,
SUM(sales_amount) AS total_revenue
FROM [DataWarehouseAnalytics].[gold].[fact_sales] f
LEFT JOIN  [DataWarehouseAnalytics].[gold].[dim_products] p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue


-- BY USING WINDOW FUNTION
SELECT *
FROM (
	SELECT 
	p.product_name,
	SUM(sales_amount) AS total_revenue,
	RANK() OVER(ORDER BY SUM(sales_amount) DESC) AS rank_products
	FROM [DataWarehouseAnalytics].[gold].[fact_sales] f
	LEFT JOIN  [DataWarehouseAnalytics].[gold].[dim_products] p
	ON p.product_key = f.product_key
	GROUP BY p.product_name) t
WHERE  rank_products <= 5

-- FIND THE TOP- 10 CUSTOMERS WHO HAVE GENERATED THE HIGHEST REVENUE AND 3 CUSTOMERS WITH THE FEWEST ORDER PLACED
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM [DataWarehouseAnalytics].[gold].[fact_sales] f
LEFT JOIN  [DataWarehouseAnalytics].[gold].[dim_customers] c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC


-- 3 CUSTOMERS WITH THE FEWEST ORDER PLACED
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS total_orders
FROM [DataWarehouseAnalytics].[gold].[fact_sales] f
LEFT JOIN  [DataWarehouseAnalytics].[gold].[dim_customers] c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders








